######################################################################
# Automatically generated by qmake (3.0) ?? ?? 15 23:47:04 2015
######################################################################

 QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
TARGET = sortdialog
INCLUDEPATH += .

# Input
HEADERS += sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp
