######################################################################
# Automatically generated by qmake (3.0) ?? ?? 19 21:51:15 2015
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = layout
INCLUDEPATH += .

# Input
SOURCES += layout.cpp
