######################################################################
# Automatically generated by qmake (3.0) ?? ?? 15 00:10:38 2015
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
