######################################################################
# Automatically generated by qmake (3.0) ?? ?? 26 14:15:01 2015
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
