######################################################################
# Automatically generated by qmake (3.0) ?? ?? 19 21:31:58 2015
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = quit
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
